version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - GIN_MODE=release
      - ETH_RPC=${ETH_RPC}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3000}
    volumes:
      - ./.env:/app/.env:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3004/swagger/index.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

  frontend:
    build:
      context: ./platform
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3004
    networks:
      - app-network
    depends_on:
      - api
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  app-network:
    driver: bridge 